version: '3'
services:
  frontend:
    tty: true
    stdin_open: true
    build: .
    command: npm run start
    ports:
      - "5000:3000"
    volumes:
      - ./src:/app
    environment:
      NODE_ENV: development
volumes:
  db-data:
  bundle:
